### ISSUE TITLE
How much does it take to install?

### ISSUE THREAD

**Issue by hkarakose** [romanlv/docker-testopia#1]
Can you provide information about how much it takes to install this image and how much disk space is required for this image?

**Comment by romanlv** [comment]
In terms of time, it depends on your knowledge of docker, on local computer can be done within 5-10 minutes if you know what you are doing. 

Disk space - on my local computer docker images shows: 
```
romanlv/docker-testopia 648.1 MB
dklawren/docker-bugzilla 2.7 GB
```
so I guess it's around 3Gb for the image + whatever additional space container needs to run

**Comment by hkarakose** [comment]
Thanks
